language: node_js
node_js:
  - '10'
cache:
  yarn: true

before_install:
  # upgrade Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - cd fluctuat-api && yarn && yarn test:ci && yarn lint
  - yarn build
  - cd ../fluctuat-web && yarn && yarn test:ci && yarn lint
  - yarn build --prod

deploy:
  provider: script
  skip_cleanup: true
  script: bash ../scripts/deploy.sh
  on:
    branch: master
    repo: MTES-MCT/fluctuat