language: node_js
node_js:
  - '10'
cache:
  yarn: true

jobs:
  include:
    - stage: build
      script:
        - cd fluctuat-api && yarn && yarn test
        - yarn build
    - script:
        - cd fluctuat-web && yarn && yarn test
        - yarn build --prod