language: node_js
node_js:
  - '10'
cache:
  yarn: true

before_install:
  # upgrade Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH

jobs:
  include:
    - stage: build
      script:
        - cd fluctuat-api && yarn && yarn test && yarn lint
        - yarn build
    - script:
        - cd fluctuat-web && yarn && yarn test && yarn lint
        - yarn build --prod