version: '3'
services:
  fluctuat-web:
    build:
      context: fluctuat-web
    restart: always
    network_mode: host
    ports:
      - "4200:4200"
  fluctuat-api:
    build:
      context: fluctuat-api
    restart: always
    ports:
      - "9000:9000"
    env_file: ./fluctuat-api/.env
    environment:
      DB_CLUSTER: mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./fluctuat-api/.data/fluctuat-db/:/data/db/