export class Contacts {
  customerNames;
  customerEmails;
  senderNames;
  senderEmails;
  receiverNames;
  receiverEmails;
  middlemanNames;
  middlemanEmails;
  transporterNames;
  transporterEmails;
  transporterCellphones;
  shipNames;
  shipRegNumbers;
  loadManagerEmails;
  unloadManagerEmails;
  customers;
  senders;
  receivers;
  middlemen;
  transporters;
  ships;
}
