export const PortList = [
  'Grand Port maritime du Havre',
  'Grand Port Maritime de Rouen',
  'GPMR - Honfleur',
  'GPMR - Radicatel',
  'GPMR - Wandrille',
  // Paris
  'Port de Bonneuil-sur-Marne',
  'Quai de Boulogne-Legrand',
  'Quai de la Bourdonnais',
  'Quai de Bray-sur-Seine',
  'Port de Bruyères-sur-Oise',
  'Quai de Charenton-le-Pont',
  'Quai de Clichy',
  'Quai de Conflans-Fin-d’Oise',
  'Quai de Corbeil-Essonnes',
  'Port d’Evry',
  'Port de Gennevilliers',
  'Port de Javel',
  'Quai de Lagny-sur-Marne',
  'Quai du Pecq',
  'Quai des Mureaux',
  'Port de Limay-Porcheville',
  'Quai de Meaux',
  'Quai de Montereau-Fault-Yonne',
  'Quai de Nanterre-Jules-Quentin',
  'Quai de Nanterre-Lavoisier',
  'Quai de Point-du-Jour',
  'Quai de Saint-Denis-l’Etoile',
  'Quai de Saint-Ouen-l’Aumône',
  'Quai de Tolbiac',
  // end paris
  'Port Angot (Elbeuf)',
  'Port de l’Aube',
  'Port de Châlons-en-Champagne',
  'Port de Gaillon',
  'Port de Gron Haute Bourgogne',
  'Port de Joigny',
  'Port de Longueil-Ste-Marie',
  'Port de Nogent-sur-Oise',
  'Port privé de Nogent-sur-Seine',
  'Port de Reims-Colbert',
];
